version: "3.9"

services:
  db:
    container_name: calendar-db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: calendar
    ports:
      - 5432:5432
    expose:
      - 5432
